/**
 * Application-side ports for the racing experiment. The route imports
 * `RacingTransport` from the app-local adapter, which structurally satisfies
 * this interface; both web and (eventually) desktop adapters share the
 * contract.
 */

import type {
  BestLapKey,
  LapResult,
  RacingSession,
  SectorTime,
  SetupValues,
} from '../../shared/racing/index.js';

export interface StartSessionInput {
  trackId: string;
  vehicleId: string;
  /** Optional explicit session id; otherwise generated by the transport. */
  sessionId?: string;
}

export interface RecordLapInput {
  sessionId: string;
  trackId: string;
  vehicleId: string;
  lapMs: number;
  sectors?: ReadonlyArray<SectorTime>;
  finishedAt?: string;
}

export interface RacingTransport {
  startSession(input: StartSessionInput): Promise<RacingSession>;
  recordLap(input: RecordLapInput): Promise<LapResult>;
  getBestLap(key: BestLapKey): Promise<LapResult | null>;
  getSetup(userId: string): Promise<SetupValues | null>;
  setSetup(userId: string, setup: SetupValues): Promise<void>;
}

/**
 * Persistence ports owned by `domain/infrastructure/database/racing/`.
 * Server-side use cases consume these directly; the route imports the
 * use-cases through `getRacingServices()` and never touches the repos.
 */

export interface IRacingSessionRepository {
  create(session: RacingSession): Promise<RacingSession>;
  findById(id: string): Promise<RacingSession | null>;
}

export interface ILapResultRepository {
  record(result: LapResult): Promise<LapResult>;
  bestFor(key: BestLapKey): Promise<LapResult | null>;
  list(filter?: Partial<BestLapKey>): Promise<LapResult[]>;
}

export interface IRacingSetupRepository {
  get(userId: string): Promise<SetupValues | null>;
  set(userId: string, setup: SetupValues): Promise<void>;
}
